name: flutter_food_delivery_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bottom_navy_bar: ^6.0.0
  community_material_icon: ^5.9.55
  font_awesome_flutter: ^10.3.0
  intl: ^0.18.0
  animations: ^2.0.7
  flutter_rating_bar: ^4.0.1
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/img/

  fonts:
    - family: Kantumruy Pro
      fonts:
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/kantumruy_pro/KantumruyPro-Bold.ttf
          weight: 700